Re-fetch assignment list on logout/login so the cache does not cause an endless reloading
codefreak/codefreak pull request #820
Opened 2021-02-15 11:36 UTC by HannesOlszewski

## :loudspeaker: Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## :scroll: Description

The query cache seems to cause an endless loading of the assignment list sometimes when loggin out and in again.
To stop this the assignment list should be re-fetched on login.

## :ballot_box_with_check: Checklist:

- [x] I have performed a self-review of my own code
- [x] I have run the auto code formatting scripts 
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I updated the `CHANGELOG.md`
- [ ] I have added tests that prove my fix is effective or that my feature works

2021-02-15 12:25 UTC, HenningCash requested changes
Is the bug still present on master? This might be an issue that has already been fixed in latest versions

2021-02-15 12:52 UTC, erikhofer commented
> Is the bug still present on master? This might be an issue that has already been fixed in latest versions

Also this doesn't seem like the right place to fix this. We have to make sure that the cache is invalided correctly on logout in a central place.

2021-02-18 17:16 UTC, erikhofer approved these changes

2021-02-19 09:22 UTC, HenningCash approved these changes

2021-02-19 09:22 UTC, merged